project:
  type: website
  output-dir: docs

website:
  title: "DSCI 310: Historical Horse Population in Canada"

format:
  html:
    toc: true
    toc-depth: 2
  pdf:
    toc: true
    toc-depth: 2

execute:
  echo: false

bibliography: references.bib